name: Notify Discord on issue events

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          WEBHOOK_ID: ${{ secrets.DISCORD_ISSUE_WEBHOOK_ID }}
          WEBHOOK_TOKEN: ${{ secrets.DISCORD_ISSUE_WEBHOOK_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_ACTION: ${{ github.event.action }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ACTOR: ${{ github.actor }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d @"<(cat <<EOF
          {
            "content": null,
            "embeds": [
              {
                "title": "Issue #${ISSUE_NUMBER} ${ISSUE_ACTION}",
                "url": "${ISSUE_URL}",
                "description": "${ISSUE_TITLE}",
                "color": 3447003,
                "footer": {
                  "text": "by ${ACTOR}"
                }
              }
            ]
          }
          EOF
          )" \
          https://discord.com/api/webhooks/${WEBHOOK_ID}/${WEBHOOK_TOKEN}
